//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IceCreamAPI.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public string BookId { get; set; }
        public string Title { get; set; }
        public string Descr { get; set; }
        public Nullable<System.DateTime> ReleasedDate { get; set; }
        public Nullable<double> Price { get; set; }
    }
}
