//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IceCreamAPI.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderId { get; set; }
        public Nullable<int> TransactionId { get; set; }
        public Nullable<int> OrderStatusId { get; set; }
        public string ReceiverName { get; set; }
        public string DeliveryAddress { get; set; }
        public string ReceiverEmail { get; set; }
        public Nullable<long> ReceiverPhone { get; set; }
        public Nullable<double> TotalPrice { get; set; }
        public Nullable<System.DateTime> CreDate { get; set; }
    }
}
