//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IceCreamAPI.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionHistory
    {
        public int TransactionId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> FromAccId { get; set; }
        public Nullable<int> ToAccId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<short> Status { get; set; }
        public string Note { get; set; }
    }
}
