//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IceCreamAPI.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserId { get; set; }
        public Nullable<int> TransactionId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string DisplayName { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> CreDate { get; set; }
        public Nullable<short> Role { get; set; }
        public string UserToken { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
